#!/bin/bash

#   Copyright (C) 2013 Timo Kousa
#
#   This file is part of HLS On Demand.
#
#   HLS On Demand is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   HLS On Demand is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with HLS On Demand.  If not, see <http://www.gnu.org/licenses/>.

test -s /etc/hod.conf && source /etc/hod.conf
test -z "${WORKDIR}" && WORKDIR='/tmp/hod'

TEMP=$(getopt -n ${0} -o ht: -- "${@}")
if [ ${?} != 0 ]; then
	echo "Usage: ${0} [options] /www/data/dir"
	exit 1
fi

eval set -- "${TEMP}"

while true; do
	case "${1}" in
		-h)
			echo "A script to clean HOD datadir from files not accessed recently"
			echo
			echo "Usage: ${0} [options] /www/data/dir"
			echo
			echo "Options:"
			echo " -t <sec>  time to keep files (default: 604800)"
			echo
			exit ;;
		-t)
			LIMIT=${2}
			shift 2 ;;
		--)
			shift
			break ;;
	esac
done

DATADIR=${1}

if [ -z "${DATADIR}" ]; then
	echo "Usage: ${0} [options] /www/data/dir"
	exit 1
fi

test -z "${LIMIT}" && LIMIT=604800

epoch=$(date +%s)

for file in $(ls ${WORKDIR}/*.timestamp 2>/dev/null); do
	mtime="$(stat -c %Y ${file})"

	if [ $((mtime + LIMIT)) -le ${epoch} ]; then
		key=$(basename ${file} .timestamp)

		test -z "${key}" && continue

		rm -f ${DATADIR}/${key}/*
		rmdir ${DATADIR}/${key}
		rm -f ${WORKDIR}/${key}.*
	fi
done
